### ISSUE TITLE
Hi a little comiler error on current u51 version 

### ISSUE THREAD

**Issue by istavang** [jm991/UnityThirdPersonTutorial#6]
![comilererror](https://cloud.githubusercontent.com/assets/1896130/8711195/25e18d5e-2b50-11e5-9fae-b78c3dd9aabb.PNG)

to  information 

thanks 
Dan

**Comment by khitsuji** [comment]
Go to those lines and replace `ParentHig` with `transform` (that error was caused because `ThirdPersonCamera` used to have a variable of type `ParentHig` or something like that, but now he's changed it.)

![image](https://cloud.githubusercontent.com/assets/17071033/12834125/5867590c-cb8c-11e5-991d-0a47afcdd495.png)

**Comment by jm991** [comment]
If you pull the latest, this is fixed.
